name: A workflow for my Hello World file
on:
  workflow_dispatch:
  push:
    branches: 
     - main 
    paths:
     -'website/**'
  pull_request:
    branches:
     - main
    paths:
     - 'website/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: echo Hello world
        run: echo Hello world
      - name: Install dependencies
        run: echo Install dependencies

      - name: Index.html content
        run: |
          echo "This is from INdex.html"
          cat Index.html
